import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";
import Appbar from "@/app/components/Appbar";
import SignInPanel from "./components/SignInPanel";
import { ToastContainer } from "react-toastify";

const karla = Karla({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased`}>
        <Providers>
          <Appbar>
            <SignInPanel />
          </Appbar>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
